services:
  alloy:
   container_name: alloy
   image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.8.2}
   ports:
     - 12345:12345
     - 4317:4317
     - 4318:4318
   network_mode: "host"
   volumes:
     - ./config.alloy:/etc/alloy/config.alloy
     - /var/run/docker.sock:/var/run/docker.sock
     - /run/systemd/journal:/run/systemd/journal:ro
     - /var/log/journal:/var/log/journal:ro
     - /etc/machine-id:/etc/machine-id:ro
   command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
   restart: always

