# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alertmanager:9093
rule_files:
 - rules.yml
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets:
        - prometheus:9090
 
  - job_name: grafana
    scrape_interval: 15s
    static_configs:
      - targets:
        - grafana:3000

  - job_name: cadvisor
    scrape_interval: 15s
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: node-exporter
    scrape_interval: 15s
    static_configs:
      - targets:
        - node-exporter:9100

  - job_name: 'uptime'
    scrape_interval: 30s
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: 
          - 192.168.0.10:3001
    basic_auth: # Only needed if authentication is enabled (default) 
      username: viktor
      password: wosm2025  
#########################
####INTERNAL MACHINE#####
#########################        
  - job_name: cadvisor intenal
    scrape_interval: 15s
    static_configs:
      - targets:
        - 192.168.10.10:9112

  - job_name: node-exporter internal
    scrape_interval: 15s
    static_configs:
      - targets:
        - 192.168.10.10:9110

#  - job_name: nextcloud TODO

#  - job_name: clamav TODO

####################
####DMZ MACHINE#####
####################
  - job_name: cadvisor dmz
    scrape_interval: 15s
    static_configs:
      - targets:
        - 192.168.20.10:9112

  - job_name: node-exporter dmz
    scrape_interval: 15s
    static_configs:
      - targets:
        - 192.168.20.10:9110

  - job_name: wordpress
    scrape_interval: 15s
    metrics_path: /wp-json/prompress/v1/metrics
    static_configs:
      - targets:
        - 192.168.20.10:8081

 # - job_name: Nginx Proxy TODO
       

#########################
#####NETWORK ROUTERS#####
#########################   
  - job_name: opnsense-cloud
    scrape_interval: 15s
    static_configs:
      - targets:
        - 192.168.0.1:9100

  - job_name: pfsense-cloud
    scrape_interval: 15s
    static_configs:
      - targets:
        - 192.168.0.2:9100

  - job_name: crowdsec-opnsense
    scrape_interval: 15s
    static_configs:
      - targets:
        - 192.168.20.1:6060

  - job_name: opnsense-onPrem
    scrape_interval: 15s
    static_configs:
      - targets:
        - 10.16.16.1:9100

  - job_name: pfsense-onPrem
    scrape_interval: 15s
    static_configs:
      - targets:
        - 10.16.16.2:9100

#########################
#####     Onprem    #####
######################### 

  - job_name: cadvisor mirror
    scrape_interval: 15s
    static_configs:
      - targets:
        - 172.16.10.7:9112

  - job_name: node-exporter mirror
    scrape_interval: 15s
    static_configs:
      - targets:
        - 172.16.10.7:9110

  - job_name: cadvisor wazuh
    scrape_interval: 15s
    static_configs:
      - targets:
        - 172.16.0.5:9112

  - job_name: node-exporter wazuh
    scrape_interval: 15s
    static_configs:
      - targets:
        - 172.16.0.5:9110

  - job_name: node-exporter radius
    scrape_interval: 15s
    static_configs:
      - targets:
        - 172.16.0.3:9110