groups:
  - name: Count greater than 5
    rules:
      - alert: CountGreaterThan5
        expr: ping_request_count > 5
        for: 5s

  - name: Service Down
    rules:
      - alert: MonitorDown
        expr: monitor_status{monitor_type!="group"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.monitor_name }} is DOWN"
          description: "Monitor {{ $labels.monitor_name }} (type={{ $labels.monitor_type }}) has been DOWN for more than 30s."

      - alert: MonitorPending
        expr: monitor_status{monitor_type!="group"} == 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "{{ $labels.monitor_name }} is PENDING"
          description: "Monitor {{ $labels.monitor_name }} has been in PENDING status for over 5m. Check if checks are stuck."

  - name: High Latency
    rules:
      - alert: HighResponseTime
        expr: monitor_response_time{monitor_type=~"http|ping"} > 200
        for: 15s
        labels:
          severity: warning
        annotations:
          summary: "High response time on {{ $labels.monitor_name }}"
          description: "Response time is >200ms (currently {{ $value }}ms) for more than 15s."

      - alert: ElevatedLatencyRatio
        expr: |
          (
            sum_over_time(monitor_response_time{monitor_type=~"http|ping"}[5m])
            /
            count_over_time(monitor_response_time{monitor_type=~"http|ping"}[5m])
          ) > 200
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High average latency"
          description: "Average response time over the last 5m exceeds 200ms."

  - name: Uptime SLA Breach
    rules:
      - alert: UptimeBelowSLA
        expr: |
          (
            sum_over_time(monitor_status{monitor_type!="group"}[1h])
            /
            count_over_time(monitor_status{monitor_type!="group"}[1h])
          ) < 0.99
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Uptime below 99% SLA"
          description: >
            Uptime for all services has dropped below 99% in the past hour.
            Please investigate any outages or intermittent failures.
