groups:
  
  # Alerting System Level
  - name: system-alerts
    rules:
      - alert: HighCPUUsage
        expr: (1 - avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance,job)) * 100 > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.job }}"
          description: "CPU usage has been above 50% for at least 5 minutes on {{ $labels.instance }})."

      - alert: HighMemoryUsage
        expr: 100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[5m]) + avg_over_time(node_memory_Cached_bytes[5m]) + avg_over_time(node_memory_Buffers_bytes[5m])) / avg_over_time(node_memory_MemTotal_bytes[5m]))) > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.job }}"
          description: "Memory usage is above 50% for more than 5 minutes on {{ $labels.instance }}."

      - alert: NoMetrics
        expr: up == 0
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: "No metrics found on {{ $labels.job }}"
          description: "The instance {{ $labels.instance }} has no metrics exposed."

  # Alerting Service Level