all:
  hosts:
    wosmOnpremSwitch:
      ansible_host: 172.16.0.4
      ansible_user: damjan
      ansible_password: damjan
      ansible_network_os: ios
      ansible_connection: network_cli
      ansible_ssh_common_args: '-o KexAlgorithms=+diffie-hellman-group1-sha1 -o Ciphers=+aes128-cbc -o MACs=+hmac-sha1 -o HostKeyAlgorithms=+ssh-rsa'
    gitea:
      ansible_host: 172.16.0.6
      ansible_user: debian-gitea
      ansible_password: wosm2025
      ansible_become_password: wosm2025
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    data-mirror:
      ansible_host: 172.16.0.7
      ansible_user: ubuntu-mirror
      ansible_password: wosm2025
      ansible_become_password: wosm2025
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
